---
# tasks file for ansible-role-fedora-workstation

- name: Load variables
  ansible.builtin.include_vars:
    dir: vars

- name: Execute tasks to add repositories
  ansible.builtin.import_tasks:
    file: repositories.yml

- name: Execute tasks for default applications
  ansible.builtin.import_tasks:
    file: applications.yml

# - name: Configure Gnome desktop environment
#   ansible.builtin.import_tasks:
#     file: desktop_env.yml