---
# tasks file for ansible-role-fedora-workstation

# - name: From fedora box
#   ansible.builtin.debug:
#     msg: From the updated Fedora role.

- name: Install RPM Fusion keys
  loop: "{{ rpm_fusion_keys }}"
  ansible.builtin.rpm_key:
    key: "{{ item.key }}"
    state: present

- name: Configure RPM fusion repositories
  ansible.builtin.dnf:
    name:
      - "{{ rpmfusion_free_repo }}"
      - "{{ rpmfusion_nonfree_repo }}"
    state: latest

- name: Configure additional repositories
  loop: "{{ repositories }}"
  ansible.builtin.yum_repository:
    name: "{{ item.repo_name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
    enabled: "{{ item.enabled }}"
